environment:
  NuGetAPIKey:
    secure: FLpXoL2sLMfpfmNXW9s5nL3xOavfS7ftff/2ZslUa2h3rftY1xI0ie00Zr9lnvNM
version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019
init:
- pwsh: Install-Module BuildHelpers
build_script:
- pwsh: >-
    Set-BuildEnvironment

    Update-Metadata -Path $env:BHPSModuleManifest -PropertyName ModuleVersion -Value $env:APPVEYOR_BUILD_VERSION

deploy_script:
- pwsh: Publish-Module -Path $env:APPVEYOR_BUILD_FOLDER -NuGetApiKey $env:NuGetAPIKey